spring:
  application:
    name: mall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 124.70.0.43
  session:
    store-type: redis
server:
  port: 12000
logging:
  level:
    com.zsy: debug
