spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 172.19.4.111:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 124.70.0.43
  session:
    store-type: redis

server:
  port: 20000
