spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
#      sms:
#        host: https://fesms.market.alicloudapi.com
#        path: /sms/
#        skin: 1
#        sign: 175622
#        appcode: b0563c23aff8428c97a54d4f7f9e28e5
      access-key: LTAI5tLnAoXLU83hsptQCxZP
      secret-key: XIwx6OjZRBwOG4Jy4smfOT4HUOscui
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: gulimall-zsl01
  application:
    name: mall-third-party

server:
  port: 30000
